lang: en
title: Justin Carlson
description: Probably cultivating code or lost in 3D space.
image: https://justincarlson.io/images/favicon.svg
url: https://justincarlson.io
source_url: https://github.com/justinbot/justinbot.github.io
